---
engines:
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
    enabled: false
    channel: "beta"
ratings:
  paths:
  - "**.java"
  - "**.ptjava"
exclude_paths: []
